# Generated by Django 4.1.7 on 2023-04-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KtxUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_index=True, max_length=30)),
                ('pwd', models.CharField(blank=True, db_index=True, max_length=50)),
                ('email', models.CharField(blank=True, db_index=True, max_length=50)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=11)),
                ('creation_date', models.CharField(default='-1', max_length=50)),
            ],
            options={
                'db_table': 'ktx_user',
            },
        ),
    ]
