# Generated by Django 3.1.1 on 2023-04-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktxmacro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, db_index=True, max_length=30)),
                ('expl', models.CharField(blank=True, db_index=True, max_length=100)),
            ],
            options={
                'db_table': 'paycode',
            },
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=30)),
                ('dprtr_sttn', models.CharField(blank=True, db_index=True, max_length=15)),
                ('arrvl_sttn', models.CharField(blank=True, db_index=True, max_length=15)),
                ('pay_code', models.CharField(blank=True, max_length=10)),
                ('payments', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'user_history',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=30)),
                ('username', models.CharField(blank=True, db_index=True, max_length=30)),
                ('email', models.CharField(blank=True, db_index=True, max_length=50)),
                ('membership_no', models.CharField(blank=True, db_index=True, max_length=30)),
                ('dflt_dprtr_sttn', models.CharField(blank=True, db_index=True, max_length=15)),
                ('dflt_arrvl_sttn', models.CharField(blank=True, db_index=True, max_length=15)),
                ('pay_method', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'ktx_user_info',
            },
        ),
        migrations.RemoveField(
            model_name='ktxuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ktxuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='ktxuser',
            name='id',
            field=models.CharField(blank=True, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ktxuser',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='ktxuser',
            name='pwd',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
