# Generated by Django 3.1.1 on 2023-04-20 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ktxmacro', '0002_auto_20230414_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='pay_method',
            new_name='pay_code',
        ),
    ]
