# Generated by Django 3.1.1 on 2023-04-21 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ktxmacro', '0003_auto_20230420_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
